### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#30]
Trying to create RE-Input from the example in https://github.com/Open-Systems-Pharmacology/QualificationPlan/pull/126 (also attached [Input.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/3121882/Input.zip))

<details><summary>Exception</summary>
fail: Theophylline[0]
      Object reference not set to an instance of an object.
info: Theophylline[0]

info: Theophylline[0]
      Stack trace:
info: Theophylline[0]
      at PKSim.Infrastructure.Services.PopulationExportTask.getProjectMetaInfo(String description)
info: Theophylline[0]
         at PKSim.Infrastructure.Services.PopulationExportTask.exportVectorialParametersContainerToCSV[T](T advancedParameterContainer, Func`2 createData, String fileFullPath, String fileDescription)
info: Theophylline[0]
         at PKSim.Infrastructure.Services.PopulationExportTask.ExportToCSV(PopulationSimulation populationSimulation, String fileFullPath)
info: Theophylline[0]
         at PKSim.CLI.Core.Services.SimulationExporter.<exportPopulationSimulationToCsvAsync>d__14.MoveNext()
info: Theophylline[0]
      --- End of stack trace from previous location where exception was thrown ---
info: Theophylline[0]
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
info: Theophylline[0]
         at PKSim.CLI.Core.Services.ExportSimulationRunner.<ExportSimulation>d__9.MoveNext()
info: Theophylline[0]
      --- End of stack trace from previous location where exception was thrown ---
info: Theophylline[0]
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
info: Theophylline[0]
         at PKSim.CLI.Core.Services.ExportSimulationRunner.<ExportSimulationsIn>d__8.MoveNext()
info: Theophylline[0]
      --- End of stack trace from previous location where exception was thrown ---
info: Theophylline[0]
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
info: Theophylline[0]
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
info: Theophylline[0]
         at PKSim.CLI.Core.Services.QualificationRunner.<RunBatchAsync>d__10.MoveNext()
info: Theophylline[0]
       --- End of inner exception stack trace ---
info: Theophylline[0]
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
info: Theophylline[0]
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
info: Theophylline[0]
         at System.Threading.Tasks.Task.Wait()
info: Theophylline[0]
         at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command)
info: Theophylline[0]
      Qualification run finished
fail: Qualification Runner[0]
      Project configuration for 'Theophylline' is invalid. Please check log file at 'C:\SW-Dev\PK-Sim\QualificationPlan\examples\PopulationTimeProfile\Reporting_Engine_Input\temp\Theophylline\log.txt' for details.
fail: Qualification Runner[0]
      Qualification run failed
</details>

[logfile.txt](https://github.com/Open-Systems-Pharmacology/QualificationPlan/files/3121869/logfile.txt)

QualiRunner called like this:
`QualificationRunner -i C:\Input\quali_plan.json -o C:\RE_Input -n report_quali_plan.json -l C:\logfile.txt -p C:\PK-Sim_7.5.0`

**Comment by msevestre** [comment]
The error is coming from PKSim...

**Comment by msevestre** [comment]
Yes issue with PKSim
